### ISSUE TITLE
Reading camera IP, undefined struct

### ISSUE THREAD

**Issue by denglerchr** [jwahlstrand/AravisCameras.jl#3]
Hello again, I ran into some more issues when trying to figure out the camera ip. Maybe you can also help here.

First I tried to figure out what configuration the camera has, but it seems some required structure is not defined.
```julia
julia> mode = AravisCameras.G_.get_ip_configuration_mode(device)
ERROR: UndefVarError: `GvIpConfigurationMode` not defined in `AravisCameras.G_`
Suggestion: check for spelling errors or missing imports.
Stacktrace:
 [1] get_ip_configuration_mode(instance::ArvGvDeviceLeaf)
   @ AravisCameras.G_ C:\Users\dengl\.julia\packages\AravisCameras\mW49l\src\gen\aravis_methods:2662
 [2] top-level scope
   @ REPL[67]:1
```

What worked was getting a GLib.GInetAddressLeaf object. Unfortunately I couldnt find any way to retrieve the ip from that object. Do you know of a way to get the ip information?
```julia
ip = AravisCameras.G_.get_current_ip(device)
```

**Comment by jwahlstrand** [comment]
Oops -- should work now. It looks like you can call `GLib.G_.to_string(ip)` to get the IP address. Here's some docs: https://docs.gtk.org/gio/class.InetAddress.html

**Comment by denglerchr** [comment]
Thanks!
