### ISSUE TITLE
** (julia:39417): CRITICAL **: 10:52:33.031: arv_buffer_get_status: assertion 'ARV_IS_BUFFER (buffer)' failed

### ISSUE THREAD

**Issue by denglerchr** [jwahlstrand/AravisCameras.jl#4]
Good morning,
I am back with an issue that is unfortunately happening almost randomly after a certain time. I checked on 2 computers, however, and the issue keeps appearing. Ever seen seomthing like this?
After collecting frames for a certain time, I receive errors looking as below:
![Screenshot From 2024-12-06 10-41-44](https://github.com/user-attachments/assets/df9eb569-13f6-46cc-877c-91ce2d2db5fc)
![Screenshot From 2024-12-06 10-50-20](https://github.com/user-attachments/assets/325bca2f-9252-4a78-a6b4-4834c2e9b730)
![Screenshot From 2024-12-06 10-53-04](https://github.com/user-attachments/assets/50333ebe-6809-4fff-8d71-63f2e300f291)

After these errors, the Julia Repl is frozen, I usually have to close the terminal.
My code is really similar to your code in the test folder, nothing fancy:
```julia
"""
    start_acquisition(cam::LaserLineScanner, frame_channel::Channel{FrameData}; nbuffers::Int = 2, run::Ref{Bool} = Ref(true))

Start the camera aquisition and put the frames in a Channel. Acquisition can be stopped by setting `run.x = false`
"""
function start_acquisition(vr_cam::VRMagicCam, frame_channel::Channel{FrameData}; nbuffers::Int = 2, runtask::Ref{Bool} = Ref(true))::Nothing
    @assert(nbuffers > 0)
    cam = vr_cam.cam

    # create a stream where we can put an retrieve buffers
    println("Starting camera acquisition.")
    stream = AravisCameras.create_stream(cam)
    isnothing(stream) && error("Failed to create stream")

    stream.packet_timeout = 20*1000
    stream.frame_retention = 100*1000
    payload = AravisCameras.payload(cam)
    for _ = 1:nbuffers
        push!(stream, AravisCameras.ArvBuffer(payload))
    end

    # start camera and acquisition
    sleep(0.1)
    G_.start_acquisition(cam)
    sleep(0.4)
    
    while runtask.x
        # see if the camera put something in the buffer
        buf::ArvBuffer = pop!(stream)
        
        while !try_check_status_success(buf)
            push!(stream, buf)
            println("Attempting to get another buffer")
            buf = pop!(stream)
        end

        try
            # here I extract data from buff and apply some scaling etc 
            ...
        catch e
            println(e)
        end
        push!(stream, buf)
    end

    G_.stop_acquisition(cam)
    return nothing
end
```

Versioninfo:
```julia
Julia Version 1.11.2
Commit 5e9a32e7af2 (2024-12-01 20:02 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, skylake)
Threads: 4 default, 0 interactive, 2 GC (on 4 virtual cores)

pkg> status AravisCameras
Project Laser2MQTT v0.1.0
Status `~/Desktop/Laser2MQTT.jl/Project.toml`
  [96dddf8c] AravisCameras v0.1.0 `https://github.com/jwahlstrand/AravisCameras.jl#master`

```

**Comment by denglerchr** [comment]
I noticed I left out the `try_check_status_success`. I tried wrapping it in a try catch block to avoid the error, but it didnt help.
```julia
"""
Try checking if the frame is valid. Sometimes G_.get_status returns an error unfortunately.
"""
function try_check_status_success(buffer::G_.ArvBuffer)
    try
        return G_.get_status(buffer) == AravisCameras.BufferStatus_SUCCESS
    catch e
        println(e)
    end
    return false
end
```

**Comment by jwahlstrand** [comment]
The CRITICAL error message is being emitted by aravis and it doesn't lead to a Julia exception... It looks like sometimes the buffer you get from `pop!` is not valid somehow. I just looked at my code for streaming and remembered that I use `try_pop_buffer`, which returns `nothing` if there's no buffer available. What I settled on is the following:
```
process_buffer(stream, ::Nothing) = nothing
function process_buffer(stream, buf::ArvBuffer)
    status = AravisCameras.G_.get_status(buf)
    if status != AravisCameras.BufferStatus_SUCCESS
        push!(stream,buf)
        @async println("buffer status $status")
        return
    end
    
    # do something with buf here

    push!(stream,buf)
end

function get_frame(t::Timer)
    isopen(t) || return
    n_output = n_output_buffers(stream)
    if n_output == 0
        return
    end
    while n_output_buffers(stream) > 1
        AravisCameras.try_pop_buffer(stream)
    end
    buf = AravisCameras.try_pop_buffer(stream)
    process_buffer(stream, buf)
end

t = Timer(get_frame, 0.5, interval=0.1)
```

This isn't totally robust either unfortunately, but I haven't seen it take Julia down. Sometimes things get into a funny state and frames stop appearing. Restarting acquisition usually fixes it. In contrast, in my C program streaming is extremely reliable, so there seems to be room for improvement here.

I will add that even when using the C library in a C program, every time I have used a camera from a new company I have had to adapt my approach somewhat because the new camera behaves differently. It would be nice to make things robust enough to stop having to do this.

This weekend I will clean up my code and add a new example.

**Comment by denglerchr** [comment]
Yeah, this whole GeniCAM is not the easiest to work with. I guess nothing can be done then for this error from Julia side, looks like the [pop_buffer](https://aravisproject.github.io/aravis/aravis-stable/method.Stream.pop_buffer.html) function or my camera might not be very reliable. Thanks for the hints, Ill try out some of these workarounds.
