### ISSUE TITLE
REPL hanging when 'using AravisCameras' with more than one thread

### ISSUE THREAD

**Issue by denglerchr** [jwahlstrand/AravisCameras.jl#5]
I noticed that the library seems to have some negative effect when starting Julia with more than a single thread.
To reproduce just:
julia -t 2
using AravisCameras
then write anything in the REPL

Since one doesnt actually have to use any functionality, I guess the __init__() function is what is causing this=

**Comment by jwahlstrand** [comment]
I have a lot of code that used to work fine with multiple threads... This seems to be a new issue with Gtk4 on Julia 1.11.

**Comment by jwahlstrand** [comment]
Closing here since this is definitely a Gtk4 issue: see https://github.com/JuliaGtk/Gtk4.jl/issues/78

**Comment by jwahlstrand** [comment]
The hang only seems to occur if you have multiple threads in the same pool as the one used by Gtk4. So if you start Julia with `julia -t 2,1` you can have 2 default threads and 1 interactive thread.

**Comment by denglerchr** [comment]
Thanks, Ill give this and maybe Julia 1.10 a try.
